Models/Kid.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OliveKids.Models
{
    [Table("Kid")]
    public class Kid
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayName("Arabic name")]
        public string ArabicName { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        [MaxLength(2000)]
        [MinLength(50)]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required]
        public string Gender { get; set; }
        public Sponsor Sponsor { get; set; }
        [NotMapped]
        public bool Sponsored { get; set; }
        [NotMapped]
        public string GridPhoto
        {
            get
            {
                return string.Format(@"{0}.jpg", Id);
            }
        }
        [NotMapped]
        public string Photo
        {
            get
            {
                return string.Format(@"Kids/{0}.jpg", Id);
            }
        }
        [NotMapped]
        public int Age
        {
            get
            {
                // Save today's date.
                var today = DateTime.Today;
                // Calculate the age.
                var age = today.Year - DateOfBirth.Year;
                // Go back to the year the person was born in case of a leap year
                if (DateOfBirth.Date > today.AddYears(-age)) age--;
                return age;
            }
        }
    }

}

Controllers/KidsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OliveKids.Models;
using OliveKids.Repository;

namespace OliveKids.Controllers
{
    public class KidsController : Controller
    {
        private readonly OkSposershipContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public KidsController(OkSposershipContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Sponsored(DataSourceLoadOptions loadOptions)
        {
            var kids = _context.Kids
                .Where(p => p.Sponsor != null)
                .Select(i => new
                {
                    i.Id,
                    i.Name,
                    i.ArabicName,
                    i.Age,
                    i.Gender,
                    i.GridPhoto,
                    i.Photo
                });
            return View("Grid",kids);
        }

        [HttpGet]
        public IActionResult Available(DataSourceLoadOptions loadOptions)
        {
            var kids = _context.Kids
                .Where(p => p.Sponsor == null)
                .Select(i => new
                {
                    i.Id,
                    i.Name,
                    i.ArabicName,
                    i.Age,
                    i.Gender,
                    i.GridPhoto,
                    i.Photo
                }).ToListAsync();
            return View("Grid", kids);
        }

        [HttpGet]
        public IActionResult Total(DataSourceLoadOptions loadOptions)
        {
            var kids = _context.Kids
                .Select(i => new
                {
                    i.Id,
                    i.Name,
                    i.ArabicName,
                    i.Age,
                    i.Gender,
                    i.GridPhoto,
                    i.Photo
                });
            return View("Grid", kids);
        }

        [HttpGet]
        public IActionResult Get(DataSourceLoadOptions loadOptions)
        {
            var kids = _context.Kids
                .Where(p => p.Sponsor == null)
                .Select(i => new
                {
                    i.Id,
                    i.Name,
                    i.ArabicName,
                    i.Age,
                    i.Gender,
                    i.GridPhoto,
                    i.Photo
                });
            return Json(DataSourceLoader.Load(kids, loadOptions));
        }

        [HttpGet]
        public IActionResult GetAll(DataSourceLoadOptions loadOptions)
        {
            var index = loadOptions.Filter != null ? loadOptions.Filter.IndexOf(nameof(Kid.Sponsored)) : -1;
            if (index != -1)
            {

                var flag = Convert.ToBoolean(loadOptions.Filter[index + 2]);
                var sKids = _context.Kids;
                if (flag)
                {
                    sKids.Where(p => p.Sponsor != null);
                }
                else
                {
                    sKids.Where(p => p.Sponsor == null);
                }


                // Remove the filter from options
                for (int i = 0; i < 3; i++)
                {
                    loadOptions.Filter.RemoveAt(index);
                }

                sKids.Select(i => new
                {
                    i.Id,
                    i.Name,
                    i.Age,
                    i.Gender,
                    i.ArabicName,
                    i.GridPhoto,
                    i.Photo
                });
                return Json(DataSourceLoader.Load(sKids, loadOptions));
            }
            var kids = _context.Kids
               .Select(i => new
               {
                   i.Id,
                   i.Name,
                   i.Age,
                   i.Description,
                   i.Gender,
                   i.ArabicName,
                   i.GridPhoto,
                   i.Photo
               });

            return Json(DataSourceLoader.Load(kids, loadOptions));
        }

        // GET: Kids
        public async Task<IActionResult> Index()
        {
            return View(await _context.Kids.ToListAsync());
        }

        // GET: Kids/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kid = await _context.Kids
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kid == null)
            {
                return NotFound();
            }

            return View(kid);
        }

        // GET: Kids/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kids/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DateOfBirth,Description")] Kid kid)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kid);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kid);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateKid(int id, string name, string arabicName, DateTime dateOfBirth, string description, IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                if (photo != null)
                {
                    Kid kid = new Kid()
                    {
                        Id = id,
                        Name = name,
                        ArabicName = arabicName,
                        DateOfBirth = dateOfBirth,
                        Description = description
                    };

                    SaveFile(photo, kid.Id);

                    _context.Kids.Add(kid);
                    _context.SaveChanges();
                    ViewBag.KidName = kid.Name;

                    return View("SubmissionSuccessful");
                }
            }
            return View("SubmissionFailed");
        }
        // GET: Kids/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kid = await _context.Kids.FindAsync(id);
            if (kid == null)
            {
                return NotFound();
            }
            return View(kid);
        }

        // POST: Kids/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DateOfBirth,Description")] Kid kid)
        {
            if (id != kid.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kid);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KidExists(kid.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kid);
        }

        // GET: Kids/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kid = await _context.Kids
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kid == null)
            {
                return NotFound();
            }

            return View(kid);
        }

        // POST: Kids/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var kid = await _context.Kids.FindAsync(id);
            _context.Kids.Remove(kid);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //[HttpPost]
        //public ActionResult FileSelection(string name, string arabicName, DateTime dateOfBirth, string description, IFormFile photo)
        //{

        //    if (photo != null)
        //    {
        //        Kid kid = new Kid()
        //        {
        //            Id = Guid.NewGuid(),
        //            Name = name,
        //            ArabicName = arabicName,
        //            DateOfBirth = dateOfBirth,
        //            Description = description
        //        };

        //        SaveFile(photo, kid.Id);

        //        _context.Kids.Add(kid);
        //        _context.SaveChanges();
        //        ViewBag.KidName = kid.Name;

        //        return View("SubmissionSuccessful");
        //    }

        //    return View("SubmissionFailed");
        //}

        void SaveFile(IFormFile file, int id)
        {
            try
            {
                var path = Path.Combine(_hostingEnvironment.WebRootPath, "kids");

Views/Kids/Create.cshtml
@model OliveKids.Models.Kid

@{
    ViewData["Title"] = "Create";
}

<form id="formq" method="post" enctype="multipart/form-data" asp-controller="Kids" asp-action="CreateKid">
    <div id="ff">
    @Html.HiddenFor(m => m.Photo)
        @(Html.DevExtreme().Form<OliveKids.Models.Kid>()
            .ID("form")
            .Items(items =>
            {
                items.AddGroup()
                    .CssClass("first-group")
                    .ColCount(4)
                    .Items(groupItems =>
                    {
                        groupItems.AddSimple().Template("<div class='form-avatar'></div>");
                        groupItems.AddGroup().ColSpan(3).Items(secondGroupItems =>
                        {
                            secondGroupItems.AddSimpleFor(m => m.Id);
                            secondGroupItems.AddSimpleFor(m => m.Name);
                            secondGroupItems.AddSimpleFor(m => m.ArabicName);
                            secondGroupItems.AddSimpleFor(m => m.Gender);
                            secondGroupItems.AddSimpleFor(m => m.DateOfBirth)
                                .Editor(e => e
                                    .DateBox()
                                    .Width("100%")
                                )
                                .IsRequired(true);
                        });
                    });


                items.AddGroup()
                    .CssClass("second-group")
                    .ColCount(2)
                    .Items(groupItems =>
                    {

                        groupItems.AddSimpleFor(m => m.Description)
                            .ColSpan(2)
                            .Editor(e => e
                                .TextArea()
                                .Height(140)
                            );
                    });
            })
            .FormData(Model)
        )
    
     <div id="fileuploader-container">
        @(Html.DevExtreme().FileUploader()
            .Name("Photo")
            .SelectButtonText("Select photo")
            .LabelText("")
            .Accept("image/*")
            .UploadMode(FileUploadMode.UseForm)
            
        )
    </div>
    <div class="dx-fieldset">
        @(Html.DevExtreme().ValidationSummary()
            .ID("summary")
        )

        @(Html.DevExtreme().Button()
            .ID("button")
            .Text("Update")
            .Type(ButtonType.Success)
            .UseSubmitBehavior(true)
        )
    </div>
        </div>
    </form>
















    @**@



    @*
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateOfBirth" class="control-label"></label>
                    <input asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>

        </div>
    *@
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
@*
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
    *@

Views/Kids/Delete.cshtml
@model OliveKids.Models.Kid

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kid</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Kids/Details.cshtml
@model OliveKids.Models.Kid

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Kid</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Kids/Edit.cshtml
@model OliveKids.Models.Kid

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Kid</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kids/Grid.cshtml
@{
    ViewData["Title"] = "Grid";
}

@(Html.DevExtreme().DataGrid<OliveKids.Models.Kid>()
.ShowBorders(true)
.Export(e => e.Enabled(true).FileName("OliveKids").AllowExportSelectedData(true))
.Selection(s => s.Mode(SelectionMode.Multiple))
.DataSource(d => d.Mvc().Controller("Kids").LoadAction("GetAll").Key("Id"))
.Columns(columns =>
{
columns.AddFor(m => m.Id);
columns.AddFor(m => m.Name)
         .CellTemplate(@<text>
        <div class="img" style="background-image: url(<%=data.GridPhoto%>)" />
        <span class="name"><%=data.Name%></span>
        </text>);
columns.AddFor(m => m.ArabicName);
columns.AddFor(m => m.Age);
columns.AddFor(m => m.Gender);

})
.Paging(p => p.PageSize(10))
.FilterRow(f => f.Visible(true))
.HeaderFilter(f => f.Visible(true))
.GroupPanel(p => p.Visible(true))
.Grouping(g => g.AutoExpandAll(false))
.RemoteOperations(true)
)

Views/Kids/Index.cshtml
@model IEnumerable<OliveKids.Models.Kid>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@(Html.DevExtreme().DataGrid<OliveKids.Models.Kid>()
.ShowBorders(true)
.Export(e => e.Enabled(true).FileName("OliveKids").AllowExportSelectedData(true))
.Selection(s => s.Mode(SelectionMode.Multiple))
.DataSource(d => d.Mvc().Controller("Kids").LoadAction("GetAll").Key("Id"))
.Columns(columns =>
{
columns.AddFor(m => m.Id);
columns.AddFor(m => m.Name)
         .CellTemplate(@<text>
        <div class="img" style="background-image: url(<%=data.Photo%>)" />
        <span class="name"><%=data.Name%></span>
        </text>);


columns.AddFor(m => m.Age);
columns.AddFor(m => m.Sponsored);
columns.AddFor(m => m.Gender);
columns.AddFor(m => m.ArabicName);
})
.Paging(p => p.PageSize(10))
.FilterRow(f => f.Visible(true))
.HeaderFilter(f => f.Visible(true))
.GroupPanel(p => p.Visible(true))
.Grouping(g => g.AutoExpandAll(false))
.RemoteOperations(true)
)


@*
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateOfBirth)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>
*@

Views/Kids/SubmissionFailed.cshtml
@{
    ViewData["Title"] = "SubmissionFailed";
}

<h1>Submission Failed</h1>

<p>We applogize! adding the kid did not succeed. Please <a href="~/kids/Create"> try again</a>. If this keep happening, please contact administrator</p>

Views/Kids/SubmissionSuccessful.cshtml
<h3>@ViewBag.KidName is now with Olive Kids kids squad</h3>

@(Html.DevExtreme().Button()
    .Text("Add another kid")
    .Type(ButtonType.Default)
    .Icon("refresh")
    .OnClick(@<text>
            function() {
            window.location = window.location;
            }
    </text>)
)