Models/Sponsor.cs
using Microsoft.AspNetCore.Mvc;
using OliveKids.Logic;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OliveKids.Models
{
    [Table("Sponsor")]
    [ModelBinder(BinderType = typeof(SponsorModelBinder))]
    public class Sponsor
    {
        public Sponsor()
        {
            this.SponsoredKids = new List<Kid>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [MaxLength(200)]
        public string Name { get; set; }

        [EmailAddress]
        [Required]
        public string Email { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Required]
        public string Mobile { get; set; }
        [DisplayName("Reports Language")]
        public string Language { get; set; }
        [DisplayName("Communication Preference")]
        public string CommunicationPrefrence { get; set; }
        [MaxLength(4000)]
        public string Notes { get; set; }
        [DisplayName("Payment method")]
        public string PaymentMethod { get; set; }
        public DateTime? LastConfirmationEmail { get; set; }
        
        public string Address { get; set; }

        [Required]
        public List<Kid> SponsoredKids { get; set; }
       
    }
}

Controllers/SponsorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OliveKids.Logic;
using OliveKids.Models;
using OliveKids.Repository;
using MailKit.Net.Smtp;
using MimeKit;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using System.Text;

namespace OliveKids.Controllers
{
    public class SponsorsController : Controller
    {
        private readonly OkSposershipContext _context;
        private readonly IHostingEnvironment _env = null;
        private readonly IConfiguration _configration;

        public SponsorsController(OkSposershipContext context, IHostingEnvironment env, IConfiguration configuration)
        {
            _context = context;
            _env = env;
            _configration = configuration;
        }

        // GET: Sponsors
        public async Task<IActionResult> Index()
        {
            var result = await _context.Sponsors.Include
                (sponsor => sponsor.SponsoredKids).ToListAsync();
            return View(result);
        }

        // GET: Sponsors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sponsor = await _context.Sponsors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sponsor == null)
            {
                return NotFound();
            }

            return View(sponsor);
        }

        // GET: Sponsors/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([ModelBinder(binderType: typeof(SponsorModelBinder))] Sponsor sponsor)
        {

            List<Kid> kids = new List<Kid>();
            foreach (var vKid in sponsor.SponsoredKids)
            {
                var kid = _context.Kids.Find(vKid.Id);
                kids.Add(kid);
            }

            sponsor.SponsoredKids = kids;
            _context.Sponsors.Add(sponsor);
            _context.SaveChanges();

            bool isEmailSent = SendEmailToSponsor(sponsor);

            if (isEmailSent)
            {
                sponsor.LastConfirmationEmail = DateTime.Now;
                _context.Sponsors.Update(sponsor);
                _context.SaveChangesAsync();
            }

            ViewBag.SponsorName = sponsor.Name;
            ViewBag.Kids = sponsor.SponsoredKids;
            ViewBag.IsEmailSent = isEmailSent;

            return View("SubmissionResult");

        }

        private bool SendEmailToSponsor(Sponsor sponsor)
        {
            try
            {
                var emailConfigrations = _configration.GetSection("Email");
                var senderName = emailConfigrations.GetSection("SenderName")?.Value;
                var senderEmail = emailConfigrations.GetSection("SenderEmail")?.Value;
                var userName = emailConfigrations.GetSection("Username")?.Value;
                var password = emailConfigrations.GetSection("Password")?.Value;
                var host = emailConfigrations.GetSection("Host")?.Value;
                var port = emailConfigrations.GetSection("Port")?.Value;
                var subject = emailConfigrations.GetSection("Subject")?.Value;
                var htmlBody = emailConfigrations.GetSection("HtmlBody")?.Value;
                // var textBody = emailConfigrations.GetSection("TextBody")?.Value;
                var inReplyTo = emailConfigrations.GetSection("InReplyTo")?.Value;

                MimeMessage message = new MimeMessage();

                MailboxAddress from = new MailboxAddress(senderName, senderEmail);
                message.From.Add(from);

                MailboxAddress to = new MailboxAddress(sponsor.Name, sponsor.Email);
                message.To.Add(to);

                message.Subject = string.Format(subject, sponsor.Name);


                BodyBuilder bodyBuilder = new BodyBuilder();
                StringBuilder kidHhtmlInfo = new StringBuilder();
                string rootPath = _env.WebRootPath;
                kidHhtmlInfo.Append("<table border ='1' style=' font-family: Arial; font-size: 11px;'><tr><th style='padding: 10px'>Name</th><th style='padding: 10px'>Arabic Name</th><th style='padding: 10px'>Age</th><th style='padding: 10px'> Gender </th></tr>");
                foreach (Kid kid in sponsor.SponsoredKids)
                {
                    kidHhtmlInfo.Append("<tr>");
                    var data = string.Format("<td style='padding: 10px'>{0}</td><td style='padding: 10px'>{1}</td><td style='padding: 10px'>{2}</td><td>{3}</td>", kid.Name, kid.ArabicName, kid.Age, kid.Gender);
                    kidHhtmlInfo.Append(data);
                    kidHhtmlInfo.Append("</tr>");

                    string fileName = string.Format(@"{0}\kids\{1}\{2}.jpg", rootPath, kid.Id, kid.Name);
                    bool exists = System.IO.File.Exists(fileName);
                    //string fileName = string.Format(@"{0}\kids\{1}.jpg",rootPath, kid.Id);
                    if (exists)
                    {
                        bodyBuilder.Attachments.Add(fileName);
                    }

                }

                kidHhtmlInfo.Append("</table>");


                htmlBody = string.Format(htmlBody, sponsor.Name, kidHhtmlInfo.ToString(),
                    sponsor.Name, sponsor.Mobile, sponsor.CommunicationPrefrence, sponsor.Language);
                bodyBuilder.HtmlBody = htmlBody;

                message.Body = bodyBuilder.ToMessageBody();
                message.InReplyTo = inReplyTo;


                using (SmtpClient client = new SmtpClient())
                {
                    client.Connect(host, Convert.ToInt32(port), true);
                    client.Authenticate(userName, password);
                    client.Send(message);
                    client.Disconnect(true);
                    client.Dispose();
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("error", e.Message);
                return false;
            }
            return true;
        }

        // GET: Sponsors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sponsor = await _context.Sponsors.FindAsync(id);
            if (sponsor == null)
            {
                return NotFound();
            }
            return View(sponsor);
        }

        // POST: Sponsors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Mobile,Language,CommunicationPrefrence,SponsoredKids")] Sponsor sponsor)
        {
            if (id != sponsor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sponsor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SponsorExists(sponsor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sponsor);
        }

        // GET: Sponsors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sponsor = await _context.Sponsors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sponsor == null)
            {
                return NotFound();
            }

            return View(sponsor);
        }

        // POST: Sponsors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sponsor = await _context.Sponsors.FindAsync(id);
            if (sponsor.SponsoredKids != null)
            {
                foreach (var kid in sponsor.SponsoredKids)
                {
                    //kid.Sponsor = null;
                    //_context.Kids.Update(kid);
                }
            }

            _context.Sponsors.Remove(sponsor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SponsorExists(int id)
        {
            return _context.Sponsors.Any(e => e.Id == id);
        }

    }
}

Views/Sponsors/Create.cshtml
@model OliveKids.Models.Sponsor

@{
    ViewData["Title"] = "Create";

}


@using (Html.BeginForm("Create","Sponsors",FormMethod.Post))
{
    @Html.HiddenFor( m=> m.SponsoredKids)
    @*DevExtreme addition*@
    <div id="form">
        @(Html.DevExtreme().Form<OliveKids.Models.Sponsor>()
            .ID("form")
            .Items(items =>
            {
                items.AddGroup()
                    .CssClass("first-group")
                    .ColCount(4)
                    .Items(groupItems =>
                    {
                        groupItems.AddSimple().Template("<div class='form-avatar'></div>");
                        groupItems.AddGroup().ColSpan(3).Items(secondGroupItems =>
                        {
                            secondGroupItems.AddSimpleFor(m => m.Name)
                                .IsRequired(true);
                            secondGroupItems.AddSimpleFor(m => m.Email)
                                .IsRequired(true);
                            secondGroupItems.AddSimpleFor(m => m.Mobile)
                                .IsRequired(true);
                        });
                    });


                items.AddGroup()
                    .CssClass("second-group")
                    .ColCount(1)
                    .Items(groupItems =>
                    {
                        groupItems.AddGroup().Items(secondGroupItems =>
                        {
                            secondGroupItems.AddSimpleFor(m => m.Language)
                                .IsRequired(true)
                                .HelpText("Would you like Olive Kids to translate Arabic reports & letter from Al-Amal into English?")
                                .Editor(e => e
                                    .SelectBox()
                                    .Items(new string[]{"false","true"})
                                    .DataSource(new string[] {
                                            "No thanks, I can read Arabic",
                                            "Please translate to English"
                                        }
                                    )
                                    .Value("")
                                );
                        }); ;

                        groupItems.AddGroup().Items(secondGroupItems =>
                        {
                            secondGroupItems.AddSimpleFor(m => m.CommunicationPrefrence)
                               .IsRequired(true)
                                .Editor(e => e
                                    .SelectBox()
                                    .DataSource(new string[] {
                                            "Email", "Whatsapp","SMS", "Call me"
                                        }
                                    )
                                );

                        });
                        groupItems.AddGroup().Items(secondGroupItems =>
                        {
                            secondGroupItems.AddSimpleFor(m => m.PaymentMethod)
                                .HelpText("For first payment")
                                .ColSpan(2)
                                .IsRequired(true)
                                .Editor(e => e
                                    .SelectBox()
                                    .DataSource(new string[] {
                                            "Pay by card - $600 Annual",
                                            "Pay by card - $300 Bi-Annual",
                                            "Direct debit - Please complete the form"
                                        }
                                    )
                                    .Value("")
                                );
                        });
                        groupItems.AddSimpleFor(m => m.Address)
                        .HelpText(" Only used to send letters from your sponsored child");
                        groupItems.AddSimpleFor(m => m.Notes);
                    });
            })
            .FormData(Model)

        )
    </div>
    <br/>
       <div class="dx-datagrid">
        @(Html.DevExtreme().DataGrid<OliveKids.Models.Kid>()
    .DataSource(d => d.Mvc().Controller("Kids").LoadAction("Get"))
    .Selection(s => s.Mode(SelectionMode.Multiple))
    .HoverStateEnabled(true)
    .ShowBorders(true)
    .Paging (p => p.PageSize(10))
    .FilterRow( f => f.Visible(true))
    .Columns(columns =>
    {
        columns.AddFor(m => m.Name)
        .AllowResizing(true)
        .AllowSearch(true)
        .AllowSorting(true);
        columns.AddFor(m => m.ArabicName);
        columns.AddFor(m => m.Age)
            .Width(70);
        columns.AddFor(m => m.Gender);
    })
    .OnSelectionChanged("selection_changed")

        )
    </div>
    <div id="acknowledgement"  class ="acknowledgement">
        <p>Thank you for your sponsorship! Sponsorship is an ongoing commitment that have a direct impact on your child’s quality of life.
        We understand that things change sometimes, you can cancel your sponsorship with 30 days notice, please just contact us via email, phone or live chat to do this.
        Olive Kids will attempt to contact you when your sponsorship renewal is due, or if your sponsorship direct debit fails, however if no response is received and sponsorship remains unpaid for more than 3 months, we will end the sponsorship and re-allocate the child to another sponsor.</p>
        <p>
            <span><input id ="paymentchecked" type="checkbox"></span><span> Payment made or direct debit form completed</span>
        </p>
    </div>
     <div class="dx-fieldset">
        @(Html.DevExtreme().ValidationSummary()
            .ID("summary")
        )

        @(Html.DevExtreme().Button()
            .ID("button")
            .Text("Register")
            .Type(ButtonType.Success)
            .UseSubmitBehavior(true)
            .Disabled(true)
        )
    </div>
}

<div id="employeeInfo">
    <img class="employeePhoto" />
    <p class="employeeNotes"></p>
</div>


<script>
    $(document).ready(function () {
         $('#paymentchecked').change(function() {
             if (this.checked) {
                 $('#button').removeClass("dx-state-disabled");
             }
             else {
                  $('#button').addClass("dx-state-disabled");
             }
        
    });
});
    
    function getFormInstance() {
        return $("#form").dxForm("instance");
    }

    function selection_changed(selectedItems) {
        var data = selectedItems.selectedRowsData[selectedItems.selectedRowsData.length-1];
        if (data) {
            $(".employeeNotes").text(data.Description);
            var path = "../kids/" + data.Id + ".jpg";
            $(".employeePhoto").attr("src", path);
        }

        var newData;
        for (var i = 0; i < selectedItems.selectedRowsData.length; i++) {
            if (newData === undefined) {
                newData = selectedItems.selectedRowsData[i].Id + ",";
            }
            else {
                newData += selectedItems.selectedRowsData[i].Id + ",";
            }
        }
        $('#SponsoredKids').val(newData);
    }
</script>

   @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Sponsors/Delete.cshtml
@model OliveKids.Models.Sponsor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sponsor</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CommunicationPrefrence)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CommunicationPrefrence)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentMethod)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentMethod)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Sponsors/Details.cshtml
@model OliveKids.Models.Sponsor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Sponsor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CommunicationPrefrence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CommunicationPrefrence)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Sponsors/Edit.cshtml
@model OliveKids.Models.Sponsor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Sponsor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <input asp-for="Language" class="form-control" />
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CommunicationPrefrence" class="control-label"></label>
                <input asp-for="CommunicationPrefrence" class="form-control" />
                <span asp-validation-for="CommunicationPrefrence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@*
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
    *@

Views/Sponsors/Index.cshtml
@model IEnumerable<OliveKids.Models.Sponsor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                Sponsores
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem =>  item.SponsoredKids.Count)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Sponsors/SubmissionResult.cshtml
@{
    List<OliveKids.Models.Kid> kids = ViewBag.Kids;
    string names = "";
    int i = 0;
    foreach (var kid in kids)
    {
        if (i != 0)
        {
            names = string.Format("{0} and {1}", names, kid.Name);
        }

        else
        {
            names = kid.Name;
        }
        i++;
    }
    bool isEmailSent = ViewBag.IsEmailSent;
}

<h3>Welcome @ViewBag.SponsorName</h3>
<hr/>
<p>We’re so glad to have you on board the program and we thank you for supporting Olive Kids in our mission to improve the lives of Palestinian children.</p>

<p>We’ve emailed you all these details, and we look forward to sharing with you updates from Al-Amal and your sponsored children within the next 3 months</p>

<p>Please let us know if you have any questions</p>
@*
@if (!isEmailSent)
{
    <p>A confirmation email has been sent to @ViewBag.SponsorEmail</p>
}
else
{
    <p>
        We couldn't send a confirmation email to @ViewBag.SponsorEmail! If the supported email is incorrect, please communicate with us to update the supported email.
        If this the supported email is correct, just let our adiminstration know so we fix our emailing system.
    </p>
    <p>Thank you for your contribution</p>
}
    *@
<br />

@(Html.DevExtreme().Button()
    .Text("New Sponsor")
    .Type(ButtonType.Back)
    .Icon("back")
    .OnClick(@<text>
            function() {
            window.location = window.location ;
            }
    </text>)
)

<div class="text-center home-img-footer">
    <img class="img-fluid" src="~/images/olivekids.png" />
</div>